name: flutter_background_geolocation
description: The most sophisticated background location-tracking &amp; geofencing module with battery-conscious motion-detection intelligence for iOS and Android. 
version: 0.1.7
author: Chris Scott, Transistor Software <info@transistorsoft.com>
homepage: https://github.com/transistorsoft/flutter_background_geolocation

dependencies:
  flutter:
    sdk: flutter
  device_info: ^0.2.1

flutter:
  plugin:
    androidPackage: com.transistorsoft.flutter.backgroundgeolocation
    pluginClass: FLTBackgroundGeolocationPlugin

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
  
