name: flutter_background_geolocation
description: The most sophisticated background location tracking & geofencing module with battery-conscious motion-detection intelligence for iOS and Android.
version: 4.8.4
homepage: https://github.com/transistorsoft/flutter_background_geolocation

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  background_fetch: ^1.1.2

flutter:
  plugin:
    platforms:
      android:
        package: com.transistorsoft.flutter.backgroundgeolocation
        pluginClass: FLTBackgroundGeolocationPlugin
      ios:
        pluginClass: FLTBackgroundGeolocationPlugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

